name: Continuous Integration

on:
  push:

jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'ALTER USER "${{ secrets.DB_USER }}"@"localhost" IDENTIFIED BY "${{ secrets.DB_PASSWORD }}"' 
          sudo mysql -e 'CREATE DATABASE ${{ secrets.DB_NAME }};' -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }}

      - name: Checkout Repo Code
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run linting
        run: |
          go fmt ./..
          go vet ./..

      - name: Run tests
        run: go test ./...
